
backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: home
    label: Homepage
    files:
      - file: "data/home.json"
        label: Hero
        name: hero
        fields:
          - {label: "Hero Title", name: "title", widget: "string"}
          - {label: "Hero Subtitle", name: "subtitle", widget: "text"}
          - {label: "CTA Text", name: "cta_text", widget: "string"}
          - {label: "CTA URL", name: "cta_url", widget: "string"}

  - name: prices
    label: Prices
    files:
      - file: "data/prices.json"
        label: "Prices"
        name: "prices"
        fields:
          - label: Items
            name: items
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Duration, name: duration, widget: string, required: false}
              - {label: Price, name: price, widget: string}

  - name: faq
    label: FAQ
    files:
      - file: "data/faq.json"
        label: FAQ
        name: faq
        fields:
          - label: Groups
            name: groups
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - label: Q&As
                name: qas
                widget: list
                fields:
                  - {label: Question, name: q, widget: string}
                  - {label: Answer, name: a, widget: text}

  - name: settings
    label: Booking Settings
    files:
      - file: "data/booking.json"
        label: Travel/Quote Settings
        name: booking_settings
        fields:
          - {label: Base Location, name: base, widget: string, default: "Sandton City, Johannesburg"}
          - {label: Free KM, name: free_km, widget: number, default: 50}
          - {label: Rand Per KM, name: r_per_km, widget: number, default: 4}
          - {label: Recommendation Text, name: note, widget: string, default: "1 stripper per 20 guests"}
